name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REGION: 'us-east-2'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node 14
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test --ci --coverage --maxWorkers=2
